\set ON_ERROR_STOP on
begin;
create function pg_temp.assert_true(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'FAIL: %',label; end if;end$$;
create function pg_temp.denied(statement text) returns void language plpgsql as $$begin begin execute statement; exception when insufficient_privilege then return;end;raise exception 'Expected denial: %',statement;end$$;
insert into auth.users(id,email) values('11111111-1111-1111-1111-111111111111','listener@example.invalid'),('22222222-2222-2222-2222-222222222222','other@example.invalid'),('33333333-3333-3333-3333-333333333333','editor@example.invalid');
insert into public.profiles(id,role) values('33333333-3333-3333-3333-333333333333','editor');
insert into public.singers(id,name) values('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','Discovery Choir');
insert into public.categories(id,name,slug) values('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','Praise','discovery-praise');
insert into public.tags(id,name,slug,kind) values('cccccccc-cccc-cccc-cccc-cccccccccccc','Pascha','occasion-pascha','occasion');
insert into public.mezmur(id,title,title_amharic,slug,status,lyrics_english,lyrics_amharic,singer_id,category_id,featured,legacy_aliases) values
 ('dddddddd-dddd-dddd-dddd-dddddddddddd','Discovery Song','ቅዱስ ገብርኤል','discovery-song','published','A searchable hidden lyric phrase','የምስጋና መዝሙር','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',true,array['old-discovery-url']);
insert into public.mezmur(slug,title,status) values('secret-draft','Secret Discovery Draft','draft'),('secret-archive','Secret Discovery Archive','archived');
insert into public.mezmur_tags values('dddddddd-dddd-dddd-dddd-dddddddddddd','cccccccc-cccc-cccc-cccc-cccccccccccc');
insert into public.saints(slug,title,status,body) values('discovery-saint','Discovery Saint','published','Saint body');
insert into public.prayers(slug,title,status,body) values('discovery-prayer','Discovery Prayer','published','Prayer body');
insert into public.feasts(slug,title,status,body) values('discovery-feast','Discovery Feast','published','Feast body');
insert into public.articles(slug,title,status,body) values('discovery-article','Discovery Article','published','Article body');
set local role anon;
select pg_temp.assert_true((public.discover_mezmur()->>'total')::int=1,'anonymous listings exclude drafts');
select pg_temp.assert_true((public.discover_mezmur(q=>'lyric phrase')->>'total')::int=1,'lyrics search');
select pg_temp.assert_true((public.discover_mezmur(q=>'ቅዱስ')->>'total')::int=1,'Amharic title search');
select pg_temp.assert_true((public.discover_mezmur(q=>'Choir')->>'total')::int=1,'singer search');
select pg_temp.assert_true((public.discover_mezmur(q=>'Pascha')->>'total')::int=1,'tag search');
select pg_temp.assert_true((public.discover_mezmur(language=>'om')->>'total')::int=0,'language filter');
select pg_temp.assert_true((public.discover_mezmur(language=>'am',occasion=>'occasion-pascha',featured_only=>true,singer=>'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',category=>'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb')->>'total')::int=1,'combined filters');
select pg_temp.assert_true((public.discover_mezmur(q=>'%')->>'total')::int=0,'search wildcard literal');
select pg_temp.assert_true(public.public_mezmur_detail('secret-draft') is null,'draft detail hidden');
select pg_temp.assert_true(public.public_mezmur_detail('old-discovery-url')->>'slug'='discovery-song','legacy alias');
select pg_temp.assert_true((public.search_public_content('Discovery')->>'total')::int=5,'global five content types, no drafts');
select pg_temp.assert_true(not (public.discover_mezmur()->'items'->0 ? 'lyrics_english'),'cards omit full lyrics');
select pg_temp.denied('select public.import_legacy_mezmur(''{}'',true)');
select pg_temp.denied('select * from public.mezmur_favorites');
reset role;
set local role authenticated;
set local request.jwt.claim.sub='33333333-3333-3333-3333-333333333333';
select pg_temp.assert_true((public.discover_mezmur()->>'total')::int=1,'staff public queries exclude drafts');
select pg_temp.assert_true(public.public_mezmur_detail('secret-draft') is null,'staff public detail excludes drafts');
set local request.jwt.claim.sub='11111111-1111-1111-1111-111111111111';
insert into public.mezmur_favorites(mezmur_id) values('dddddddd-dddd-dddd-dddd-dddddddddddd');
select pg_temp.assert_true((public.public_favorites()->>'total')::int=1,'ordinary listener can favorite');
select pg_temp.denied('insert into public.mezmur_favorites(user_id,mezmur_id) values(''22222222-2222-2222-2222-222222222222'',''dddddddd-dddd-dddd-dddd-dddddddddddd'')');
set local request.jwt.claim.sub='22222222-2222-2222-2222-222222222222';
select pg_temp.assert_true((select count(*)=0 from public.mezmur_favorites),'favorites private to owner');
delete from public.mezmur_favorites;
set local request.jwt.claim.sub='11111111-1111-1111-1111-111111111111';
select pg_temp.assert_true((public.public_favorites()->>'total')::int=1,'cannot delete another user favorite');
delete from public.mezmur_favorites;
select pg_temp.assert_true((public.public_favorites()->>'total')::int=0,'owner can unfavorite');
reset role;
rollback;
\echo Public discovery and favorites security passed.
