export const MEHARENE_AB_CONTENT = {
  title: 'መሐረነ አብ ሙሉ ጸሎቱ',
  transliterationTitle: 'Meharene Ab Mulu Tselotu',
  text: {
    amharic: [
      'አባት ሆይ ማረን ሃሌ ሉያ',
      'ወልድ ሆይ ማረን ሃሌ ሉያ',
      'መሐሪ መንፈስ ቅዱስ ሆይ በይቅርታህ አስበን (3 ጊዜ)',
      'ላንተ ምሥጋናን እንልካለን ላንተም ምሥጋናን እናሳርጋለን',
      'ይቅር ባይ ይቅር በለን ኃጢአታችንንም አስተስርይልን',
      'አድነንም',
      'ነፍሳችንንና ሥጋችንን ጠብቅ',
      'የእግዚአብሔር ልጅ ክርስቶስ ሆይ',
      'አምላካችን መድኃኒታችን ኢየሱስ ክርስቶስ ሆይ ይቅር በለን',
      'በምህረትህ ብዛት',
      'በደላችንን አጥፋልን',
      'ይቅርታህንም ወደኛ ላክልን',
      'ባንተ ዘንድ ነውና',
      'ይቅርታ',
      'ሃሌ ሉያ ይቅር ባይ አባት ሆይ ማረን',
      'ይቅርም በለን',
      'ይቅር ባይ ሆይ ይቅርታህን ላክ',
      'ያለፈው በደላችንን አስበህ አታጥፋን',
      'በይቅርታህ',
      'አንተ ይቅር ባይ ነህና',
      'ለሚጠሩህ ሁሉ ይቅርታህ ብዙ ነው',
      'በእውነት ለሚጠሩህ',
      'ሁልጊዜ ሰሚ ነህ',
      'በማዳን ጊዜ ቻይ ነህ',
      'ቻይ',
      'በማዳን ጊዜ',
      'ለአምላካችን ቃሉ እውነት ነው፡፡',
      'አብን እንለምነው ምሕረቱን ይላክልን',
      'አብ ለለመነው ሁሉ ይበቃልና',
      'ሃሌ ሉያ',
      'ለርሱ ምስጋና ይገባል',
      'ሃሌ ሉያ ለርሱ ምስጋና ይገባል',
      'ሃሌ ሉያ',
      'ለሁሉ ጌታ ለክርስቶስ',
      'ሃሌ ሉያ ሃሌ ሃሌ ሉያ',
      'አሁንስ',
      'ተስፋየ ማን ነው',
      'እግዚአብሔር አይደለምን',
      'አቤቱ ነፍሴን በእጅህ አደራ እሰጣለሁ',
      'ወደ ምህረት አምላክ',
      'ነፍስየን አደራ እሰጣለሁ',
      'ወደ ምስጋና ንጉሥ',
      'ነፍስየን አደራ እሰጣለሁ',
      'በጌታየና በአምላኬ',
      'ነፍስየን አስጠብቃለሁ',
      'ነፍሴን ከክፉ ሥራ ሁሉ አድናት',
      'ስጡ',
      'እንለምነው',
      'ራራልን እንበለው',
      'እውነተኛ የሆነው አምላካችን ቃሉ እውነት ነውና',
      'ሁሉን የሚችል የሚሳነው ነገር የሌለ',
      'የድሆች አምላክ የተቸገሩትን የምትረዳ',
      'እኛ ባንተ ተማጽነናል',
      'ሁሉን የሚችል የሚሳነው ነገር የሌለ',
      'የድሆች አምላክ ያዘኑትን የምታጽናና ሆይ',
      'እኛ በአንተ ተማጽነናል',
      'ሁሉን የሚችል የሚሳነው ነገር የሌለ',
      'የድሆች እና ተሥፋ ለቆረጡ አምላካቸው',
      'እኛ ባንተ ተማጽነናል',
      'ከጧት ጀምሮ እስከማታ እንደጠበቅከን ከማታ እሰከ ጧት ጠብቀን (3 ጊዜ የሚባል)',
      'አቤቱ ርስትህን ይቅር በል ሃሌ ሉያ ጸሎታችንን እና አስተብቁኦታችንን ስማ ኃጢአታችንንም ሁሉ አስተስርይልን የዕዝራ ፀሎትና ልመና የሰማህ ሆይ ምህላችንን ተቀበል ሰላምህን ስጠን ከመካከላችንም አትራቅ',
      'አቤቱ ከኛ መዓትህን መልስ ሃሌ ሉያ ያማርሽ ርግብየ እንደ እንኮይ የአፏ ሽታያማረ ንግግሯም ሀሉ ሰላም የሆነ ርግቤየ ሆይ ወደ እኔ ነይ',
      'አቤቱ ይቅርታህን አሳየን ሃሌ ሉያ፣ የሰላማችን ማደርያ ደብተራ ኦሪት የሰማዕታት እናታቸው የመላእክት እህታቸው ኑ ሁላችንም ወደ ድንግል ማርያም እንስገድ',
      'የሰላማችን መልአክ የመላእክት አለቃ ቅዱስ ሚካኤል ሆይ ስለኛ ለምን፡፡ ጸሎታችንንም ከታላቁ ንጉሥ መንበር ፊት አሳርግልን፡፡',
      'ቅዱስ ገብርኤል ድንግል ማርያምን አበሠራት እንዲህ አላት ልጅን ትወልጃለሽ ለዘለዓለሙ ለያዕቆብ ቤት ይነግሣል ለመንግቱም ፍጻሜ የለውም',
      'ቅዱስ ጊዮርጊስ ሆይ ወደ እግዚአብሔር ለምንልን ስለኛ ለምን፡፡ አረዱት ቆራረጡት ስጋውን ፈጭተው እንደ ትቢያ በተኑት፡፡ ወደ ሰባ ነገሥታት ወሰዱት ምድርን ተረገጠ ሙታንን አስነሣ፡፡ አባታችን ጊዮርጊስ በሰላም ከሞት ወደ ሕይወት ተሻገረ ርስት መንግሥተ ሰማያትንም ወረሰ፡፡',
      'ብፁዕ አባታችን አቡነ ተክለሃይማኖት በጌታው ዘንድ ዋጋን ያገኝ ዘንድ ወደ ገዳማት የገሠገሠ፡፡ ወደ ደብረ ሊባኖስ ገዳም ገባ በታላቅ ደስታና በሰላም ገባ፡፡',
      'አባ ሳሙኤል ሆይ በረከትህን እቀበል ዘንድ ባርከኝ ስለ ቅድስት ቤተ ክርስቲያን ሰላም ስትል ባርከኝ በረከትህንም እቀበላለሁ',
      'ለዓለምና ለዘለዓለም ሃሌሉያ',
      'የአብ ሰላም የወልድ ሰላም የመንፈስ ቅዱስ ሰላም በናንተ በወንድሞቻችንና በእህቶቻችን መካከል ይኑር',
      'አቤቱ ክርስቶስ ሆይ ማረን',
    ].join('\n'),
    geez: [
      'መሐረነ አብ ሃሌ ሉያ',
      'ተሣሃለነ ወልድ ሃሌ ሉያ',
      'መንፈስ ቅዱስ መሐሪ ተዘከረነ በሣህልከ',
      'ለከ ንፌኑ ስብሐተ ወለከ ነዓርግ አኮቴተ',
      'መሐረነ መሐሪ ኃጢአተነ አስተሥሪ',
      'ወአድኅነነ',
      'ወተማህፀን ነፍሰነ ወሥጋነ',
      'ክርስቶስ ወልደ እግዚአብሔር',
      'አምላክነ ወመድኃኒነ ኢየሱስ ክርስቶስ ተሣሃለነ',
      'በብዝኃ ምህረትከ',
      'ደምስስ አበሳነ',
      'ወፈኑ ሣህለከ ዲቤነ',
      'እስመ እምኀቤከ',
      'ውእቱ ሣህል',
      'ሃሌ ሉያ መሐረነ አብ መሐሪ',
      'ወተሣሃለነ',
      'ሀብ ሣህለከ መሐሪ',
      'ኢታጥፍአነ ተዘኪረከ ዘትካት',
      'በምህረትከ',
      'እስመ መሐሪ አንተ',
      'ወብዙህ ሣህልከ ለኩሎሙ እለ ይጼውዑከ',
      'ይጼውዑከ በጽድቅ',
      'ሰማዒ ወትረ',
      'ከሃሊ ዘውስተ አድኅኖ',
      'ከሃሊ',
      'ዘውስተ አድህኖ',
      'ለአምላክነ እስመ ጽድቅ ቃሉ',
      'ንስአሎ ለአብ ይፈኑ ለነ ሣህሎ',
      'እስመ አብ የአክል ለዘሰአሎ',
      'ሃሌ ሉያ',
      'ስብሐት ሎቱ ይደሉ',
      'ሃሌ ሉያ አኮቴት ሎቱ ይደሉ',
      'ሃሌ ሉያ',
      'ለክርስቶስ ለእግዚአ ኩሉ',
      'ሃሌ ሉያ ሃሌ ሃሌ ሉያ',
      'ወይእዜኒ',
      'መኑ ተስፋየ',
      'አኮኑ እግዚአብሔር',
      'ውስተ እዴከ እግዚኦ አመኀጽን ነፍስየ',
      'ኀበ አምላከ ምህረት',
      'አመኀፅን ነፍስየ',
      'ኀበ ንጉሠ ስብሐት',
      'አመኀጽን ነፍስየ',
      'በእግዚእየ ወአምላኪየ',
      'አመኀጽን ነፍስየ',
      'እምኩሉ ምግባረ እኩይ አድኅና ለኀፍስየ',
      'ሀቡ',
      'ንስአሎ',
      'ናስተምህሮ',
      'ለአምላክነ ጻድቅ እስመ ጽድቅ ቃሉ',
      'ዘይክል ኩሎ ወአልቦ ዘይሰአኖ',
      'አምላከ ነዳያን ረዳኤ ምንዱባን',
      'ነህነ ኀቤከ ተማኅፀነ',
      'ዘይክል ኩሎ ወአልቦ ዘይሰአኖ',
      'አምላከ ነዳያን ናዛዜ ኅዙናን',
      'ንህነ ኀቤከ ተማኅፀነ',
      'ዘይክል ኩሎ ወአልቦ ዘይሰአኖ',
      'አምላከ ነዳያን ወተስፋ ቅቡፃን',
      'ንህነ ኀቤከ ተማኅፀነ',
      'ወበከመ ዐቀብከነ እምነግህ እስከ ሠርክ ዕቀበነ እግዚኦ እምሠርክ እስከ ነግህ',
      'ተሣሃልከ እግዚኦ ምድረከ ሃሌ ሉያ ስማዕ ጸሎተነ ወስዕለተነ ወስረይ ኩሎ ኃጢአተነ ስማዕ ጸሎተነ ወስዕለተነ ዘሰማዕኮ ጸሎቶ ወስዕለቶ ለዕዝራ ተወከፍ ምህላነ ሰላመከ ኀበነ ወእማዕከሌነ ኢትርሐቅ',
      'ወሚጥ መዓተከ እምኔነ ሃሌ ሉያ፤ ንዒ ኀቤየ እንቲአየ ሠናይት ርግብየ መዓዛ አፉሃ ከመ ኮል ወኩሉ ነገራ በሰላም',
      'አርእየነ እግዚኦ ሣህለከ ሃሌ ሉያ፤ ማህደረ ሰላምነ ቅድስት ደብተራ እሞሙ ለሰማዕት ወእኅቶሙ ለመላእክት ንዑ ንስግድ ኩልነ ኀበ ማርያም እምነ',
      'መልአከ ሰላምነ ሊቀ መላእክት ሚካኤል፣ ሰአል ወጸሊ በእንቲአነ አዕርግ ጸሎተነ ቅድመ መንበሩ ለንጉሥ አቢይ',
      'ገብርኤል አብሠራ ለማርያም ወይቤላ ትወልዲ ወልደ ወይነግሥ ለቤተ ያዕቆብ ለዓለም ወአልቦ ማኅለቅት ለሰላሙ።',
      'ሰዓል ለነ ጊዮርጊስ ኀበ እግዚአብሔር ወጸሊ በእንቲአነ ሀረድዎ ወገመድዎ ወዘረዉ ሥጋሁ ከመ ሐመድ ወወሰድዎ ኀበ ሰብዓ ነገሥት ረገጸ ምድረ አንስአ ሙታነ አባ ጊዮርጊስ በሰላም አደወ መንግሥተ ክብር ወረሰ',
      'ብፁዐ አባ አቡነ ተክለ ሃይማኖት ዘኤለ ገዳማተ በኀበ እግዚኡ ይንሳእ እሴተ ቦአ ገዳመ ደብረ ሊባኖስ በፍስሐ ወበሰላም',
      'ባርከኒ አባ እንሣእ በረከተከ በእንተ ሰላማ ለቅድስት ቤተ ክርስቲያን ሳሙኤል አባ ባርከኒ እንሣእ በረከተከ',
      'ለዓለም ወለዓለመ ዓለም ሃሌ ሉያ',
      'ሰላመ አብ ወሰላመ ወልድ ወሰላመ መንፈስ ቅዱስ የሃሉ ማዕከሌክሙ አኀው',
      'እግዚኦ መሐረነ ክርስቶስ',
    ].join('\n'),
    english: '',
  },
  transliteration: {
    amharic: '',
    geez: [
      'Meharene Ab hale luya',
      'Tesahalene Weld hale luya',
      'Menfes Qidus mehari tezekerene besahilke',
      'Leke nifenu sibhate weleke nearg akotete',
      'Meharene mehari hatiatene astesri',
      'Weadihnene',
      'Wetemahitsen nefesene wesigane',
      'Kristos welde Egziabher',
      'Amlakene wemedihanine Iyesus Kristos tesahalene',
      'Bebizha mihretke',
      'Demsese abesane',
      'Wefenu sahilke dibene',
      'Esme emhibeyeke',
      'Wiitu sahil',
      'Hale luya meharene Ab mehari',
      'Wetesahalene',
      'Hab sahilke mehari',
      'Itatifeane tezekireke zetikat',
      'Bemihretke',
      'Esme mehari ante',
      'Webizuh sahilke lekulomu ele yitsewuke',
      'Yitsewuke betsidik',
      'Semai wetire',
      'Kehali zewuste adihino',
      'Kehali',
      'Zewuste adihino',
      'Leamlakene esme tsidik qalu',
      'Nisealo leAb yifenu lene sahilo',
      "Esme Ab yeakil lezes'ealo",
      'Hale luya',
      'Sibhat lotu yidelu',
      'Hale luya akotet lotu yidelu',
      'Hale luya',
      'LeKristos leEgzia kulu',
      'Hale luya hale hale luya',
      'Weyezieni',
      'Menu tesfaye',
      'Akonu Egziabher',
      'Wuste ideke Egzio amehatsin nefsiye',
      'Habe Amlake mihret',
      'Amehatsin nefsiye',
      'Habe Niguse sibhat',
      'Amehatsin nefsiye',
      'BeEgziiye weAmlakiye',
      'Amehatsin nefsiye',
      'Emkulu migbare ekuy adihna lehefsiye',
      'Habu',
      'Nisealo',
      'Nastemihro',
      'Leamlakene tsadiq esme tsidik qalu',
      'Zeyikil kulo wealbo zeyiseano',
      'Amlake nedayan redae minduban',
      'Nehine hibeyeke temahitsene',
      'Zeyikil kulo wealbo zeyiseano',
      'Amlake nedayan nazaze hizunan',
      'Nihine hibeyeke temahitsene',
      'Zeyikil kulo wealbo zeyiseano',
      'Amlake nedayan wetesfa qibutsan',
      'Nihine hibeyeke temahitsene',
      'Webekeme aqebekene emnegih eske serk iqebene Egzio emserk eske negih',
      'Tesahalke Egzio midreke hale luya sima tselotene wesilatene wesirey kulo hatiatene sima tselotene wesilatene zesemako tseloto wesilato leEzira tewekef mihilane selameke hibene weimayekeleene itirhiq',
      'Wemit meateke emnene hale luya nii hibeye entiaye senayit rigbiye meaza afuha keme kol wekulu negera beselam',
      'Areyene Egzio sahilke hale luya mahidere selamene qidist debetera emomu lesemait weihitomu lemelaiikt niu nisgid kulene hibe Mariyam emine',
      'Meleake selamene liqe melaiikt Mikael seal wetseli beentiane airig tselotene qidime menberu lenigus abiy',
      'Gebriel abesera leMariyam weyibela tiwoldi welda weyinegis leBete Yaiqob lealem wealbo mahileqt leselamu',
      'Seal lene Giyorgis hibe Egziabher wetseli beentiane haredwo wegemedwo wezerawu sigahu keme hamed wewesedwo hibe seba negest regetse midre ansia mutane Aba Giyorgis beselam adewo mengiste kibir werese',
      'Bitsua Aba Abune Tekle Haymanot zeele gedamate behibe Egziu yinisae isete boa gedame Debre Libanos befisiha webeselam',
      'Barekeni Aba insae bereketeke beente selama leqidist Bete Kristiyan Samuel Aba barekeni insae bereketeke',
      'Lealem welealeme alem hale luya',
      'Selame Ab weselame Weld weselame Menfes Qidus yehalu maikelekimu ahaw',
      'Egzio meharene Kristos',
    ].join('\n'),
    english: '',
  },
  summary: {
    amharic:
      'ይህ መሐረነ አብ ሙሉ ጸሎት በግዕዝና በአማርኛ የተቀረበ የምህላ ጸሎት ነው። በውስጡ ምሕረት፣ ይቅርታ፣ መዳን፣ ጥበቃ፣ ሰላም እና የቅዱሳን ምልጃ ተካትቷል።',
    english:
      'This is the full Meharene Ab prayer presented in both Geʽez and Amharic. It is a prayer of supplication containing pleas for mercy, forgiveness, salvation, protection, peace, and the intercessions of saints.',
  },
}
