// Reviewed canonical slots and explicit source-volume assignments.
// Source book numbers and verse numbers are never rewritten to match these slots.
const old = [
  ['genesis', 'Genesis', [1]],
  ['exodus', 'Exodus', [2]],
  ['leviticus', 'Leviticus', [3]],
  ['numbers', 'Numbers', [4]],
  ['deuteronomy', 'Deuteronomy', [5]],
  ['joshua', 'Joshua', [6]],
  ['judges', 'Judges', [7]],
  ['ruth', 'Ruth', [8]],
  ['samuel', 'Samuel', [9, 10]],
  ['kings', 'Kings', [11, 12]],
  ['first-chronicles', 'First Chronicles', [13]],
  ['second-chronicles', 'Second Chronicles', [14]],
  ['jubilees', 'Jubilees', [15]],
  ['enoch', 'Enoch', [16]],
  ['ezra-nehemiah', 'Ezra and Nehemiah', [17, 18]],
  ['second-ezra-and-ezra-sutuel', 'Second Ezra and Ezra Sutuel', [19, 20]],
  ['tobit', 'Tobit', [21]],
  ['judith', 'Judith', [22]],
  ['esther', 'Esther', [23]],
  ['first-meqabyan', 'First Meqabyan', [24]],
  ['second-and-third-meqabyan', 'Second and Third Meqabyan', [25, 26]],
  ['job', 'Job', [27]],
  ['psalms', 'Psalms', [28]],
  ['proverbs', 'Proverbs', [29]],
  ['tegsats', 'Tegsats (Reproof)', [30]],
  ['wisdom', 'Wisdom of Solomon', [31]],
  ['ecclesiastes', 'Ecclesiastes', [32]],
  ['song-of-songs', 'Song of Songs', [33]],
  ['isaiah', 'Isaiah', [35]],
  ['jeremiah-collection', 'Jeremiah Collection', [36, 37, 38, 39, 40]],
  ['ezekiel', 'Ezekiel', [41]],
  ['daniel', 'Daniel', [42]],
  ['hosea', 'Hosea', [43]],
  ['amos', 'Amos', [44]],
  ['micah', 'Micah', [45]],
  ['joel', 'Joel', [46]],
  ['obadiah', 'Obadiah', [47]],
  ['jonah', 'Jonah', [48]],
  ['nahum', 'Nahum', [49]],
  ['habakkuk', 'Habakkuk', [50]],
  ['zephaniah', 'Zephaniah', [51]],
  ['haggai', 'Haggai', [52]],
  ['zechariah', 'Zechariah', [53]],
  ['malachi', 'Malachi', [54]],
  ['sirach', 'Sirach', [34]],
  ['josephas-son-of-bengorion', 'Josephas, son of Bengorion', []],
]

const newer = [
  ['matthew', 'Matthew', [55]],
  ['mark', 'Mark', [56]],
  ['luke', 'Luke', [57]],
  ['john', 'John', [58]],
  ['acts', 'Acts', [59]],
  ['romans', 'Romans', [60]],
  ['first-corinthians', 'First Corinthians', [61]],
  ['second-corinthians', 'Second Corinthians', [62]],
  ['galatians', 'Galatians', [63]],
  ['ephesians', 'Ephesians', [64]],
  ['philippians', 'Philippians', [65]],
  ['colossians', 'Colossians', [66]],
  ['first-thessalonians', 'First Thessalonians', [67]],
  ['second-thessalonians', 'Second Thessalonians', [68]],
  ['first-timothy', 'First Timothy', [69]],
  ['second-timothy', 'Second Timothy', [70]],
  ['titus', 'Titus', [71]],
  ['philemon', 'Philemon', [72]],
  ['hebrews', 'Hebrews', [73]],
  ['first-peter', 'First Peter', [74]],
  ['second-peter', 'Second Peter', [75]],
  ['first-john', 'First John', [76]],
  ['second-john', 'Second John', [77]],
  ['third-john', 'Third John', [78]],
  ['james', 'James', [79]],
  ['jude', 'Jude', [80]],
  ['revelation', 'Revelation', [81]],
  ['sirate-tsion', 'Sirate Tsion', []],
  ['tizaz', 'Tizaz', []],
  ['gitsew', 'Gitsew', []],
  ['abtilis', 'Abtilis', []],
  ['first-dominos', 'First Dominos', []],
  ['second-dominos', 'Second Dominos', []],
  ['clement', 'Clement', [82]],
  ['didascalia', 'Didascalia', [83]],
]

export const canonicalBooks = [
  ...old.map(([key, nameEn, amharicSourceNumbers], index) => ({
    key, nameEn, amharicSourceNumbers, collection: 'old', canonicalNumber: index + 1,
    sortOrder: index + 1,
  })),
  ...newer.map(([key, nameEn, amharicSourceNumbers], index) => ({
    key, nameEn, amharicSourceNumbers, collection: 'new', canonicalNumber: index + 1,
    sortOrder: old.length + index + 1,
  })),
]

export const amharicSourceMap = canonicalBooks.flatMap((book) =>
  book.amharicSourceNumbers.map((sourceBookNumber, index) => ({
    edition: 'am', canonicalBookKey: book.key, sourceBookNumber,
    sourcePart: book.amharicSourceNumbers.length > 1 ? index + 1 : null,
    sourceOrder: sourceBookNumber,
  })),
)

// WEB's 66 raw books are mapped by reviewed identity, never by the Amharic number.
// Proverbs is a single WEB volume while Amharic Proverbs and Tegsats are separate.
// It remains draft/needs_review; chapter-level alignment must be decided before publication.
const webBooks = [
  ['Genesis', 'genesis'], ['Exodus', 'exodus'], ['Leviticus', 'leviticus'],
  ['Numbers', 'numbers'], ['Deuteronomy', 'deuteronomy'], ['Joshua', 'joshua'],
  ['Judges', 'judges'], ['Ruth', 'ruth'], ['1 Samuel', 'samuel'],
  ['2 Samuel', 'samuel'], ['1 Kings', 'kings'], ['2 Kings', 'kings'],
  ['1 Chronicles', 'first-chronicles'], ['2 Chronicles', 'second-chronicles'],
  ['Ezra', 'ezra-nehemiah'], ['Nehemiah', 'ezra-nehemiah'],
  ['Esther', 'esther'], ['Job', 'job'], ['Psalms', 'psalms'],
  ['Proverbs', 'proverbs'], ['Ecclesiastes', 'ecclesiastes'],
  ['Song of Solomon', 'song-of-songs'], ['Isaiah', 'isaiah'],
  ['Jeremiah', 'jeremiah-collection'], ['Lamentations', 'jeremiah-collection'],
  ['Ezekiel', 'ezekiel'], ['Daniel', 'daniel'], ['Hosea', 'hosea'],
  ['Joel', 'joel'], ['Amos', 'amos'], ['Obadiah', 'obadiah'],
  ['Jonah', 'jonah'], ['Micah', 'micah'], ['Nahum', 'nahum'],
  ['Habakkuk', 'habakkuk'], ['Zephaniah', 'zephaniah'], ['Haggai', 'haggai'],
  ['Zechariah', 'zechariah'], ['Malachi', 'malachi'], ['Matthew', 'matthew'],
  ['Mark', 'mark'], ['Luke', 'luke'], ['John', 'john'], ['Acts', 'acts'],
  ['Romans', 'romans'], ['1 Corinthians', 'first-corinthians'],
  ['2 Corinthians', 'second-corinthians'], ['Galatians', 'galatians'],
  ['Ephesians', 'ephesians'], ['Philippians', 'philippians'],
  ['Colossians', 'colossians'], ['1 Thessalonians', 'first-thessalonians'],
  ['2 Thessalonians', 'second-thessalonians'], ['1 Timothy', 'first-timothy'],
  ['2 Timothy', 'second-timothy'], ['Titus', 'titus'], ['Philemon', 'philemon'],
  ['Hebrews', 'hebrews'], ['James', 'james'], ['1 Peter', 'first-peter'],
  ['2 Peter', 'second-peter'], ['1 John', 'first-john'], ['2 John', 'second-john'],
  ['3 John', 'third-john'], ['Jude', 'jude'], ['Revelation', 'revelation'],
]

export const webSourceMap = webBooks.map(([sourceName, canonicalBookKey], index) => ({
  edition: 'web', canonicalBookKey, sourceBookNumber: index + 1, sourceName,
  sourcePart: null, sourceOrder: index + 1,
  reviewStatus: index === 19 ? 'needs_review' : 'draft',
  mappingNote: index === 19
    ? 'WEB Proverbs 25-31 overlaps the separately counted Amharic Tegsats; review before publication.'
    : null,
}))
